version: "3.7"

services:
  npm:
    build: .
    environment:
      PROJECTS_LOCATION: ${PROJECTS_LOCATION}
      SSH_USERNAME: ${SSH_USERNAME}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}