version: "3.7"

services:
  npm:
    build: .
    environment:
      PROJECTS_LOCATION: ${PROJECTS_LOCATION}
      BIO_PATH: ${BIO_PATH}
      BIO_AUTHOR_PICTURE: ${BIO_AUTHOR_PICTURE:-${BIO_PATH}/profile-pic.jpg}
      RESUME_LOCATION: ${RESUME_LOCATION:-${BIO_PATH}/resume.md}